<!DOCTYPE html>
<!--Code by Divinector (www.divinectorweb.com)-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>How to Create responsive Homepage</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="style1.css">    
</head>
<body>
    <header>
        <H2><a href="INDEX1.php">MUSIC</a></H2>
        <nav>
            <li><a href="INDEX1.php">Home</a></li>
            <li><a href="about.php">About</a></li>
            <li><a href="index.html">Music</a></li>
            <li><a href="login.php">Login</a></li>
            <li><a href="contact.php">Contact</a></li>
        </nav>
    </header>

    <section class="banner-area">
        <div class="banner-img"></div>
            <h1>Music Website</h1>
            <h3>Responsive</h3>
            <a href="contact.php" class="banner-btn">Contact us</a> 
    </section>

    <section class="about-area" id="about">
        <h3 class="section-title">About Us</h3>
        <ul class="about-content">
            <li class="about-left"></li>
            <li class="about-right">
                <h2>About Our Company</h2>
                <p>The Indian Music Industry (IMI) is a trust that represents the recording industry distributors in India. It was founded on February 28, 1936 as Indian Phonographic Industry (IPI). It is the 2nd oldest music industry organization in the world that was involved in protecting copyrights of music producers and supporting growth of music entertainment industry.</p>
                <a href="" class="about-btn">Learn more</a>
            </li>
        </ul>
    </section>

    <section class="service-area" id="services">
        <h3 class="section-title">Services</h3>
        <ul class="services-content">
            <li>
                <i class="fa fa-music"></i>
                <h4>Remix</h4>
                <p>The Indian Music Industry (IMI) is a trust that represents the recording industry distributors in India.</p>
            </li>


            <li>
                <i class="fa fa-play"></i>
                <h4>Pop-up songs</h4>
                <p>The Indian Music Industry (IMI) is a trust that represents the recording industry distributors in India.</p>
            </li>


            <li>
                <i class="fa fa-headphones"></i>
                <h4>Bollywood</h4>
                <p>The Indian Music Industry (IMI) is a trust that represents the recording industry distributors in India.</p>
            </li>
        </ul>
    </section>

    <section class="contact-area" id="contact">
        <h3 class="section-title">Contact</h3>
        <ul class="contact-content">
            <li>
                <i class="fa fa-map-marker"></i>
                <p>Mumbai, Maharashtra <br>India</p>
            </li>

            <li>
                <i class="fa fa-phone"></i>
                <p>1234567890 <br>1234567890</p>
            </li>

            <li>
                <i class="fa fa-map-marker"></i>
                <p>ancd@gmail.com<br>abcd.com</p>
            </li>
        </ul>
    </section>

    <footer>
        <p>All Right Reserved</p>
    </footer>
</body>
</html>
